imports:
    - { resource: config.yml }

framework:
    router:
        resource: "@RestBundle/Resources/config/routing.yml"
    serializer:
        enabled: true
    translator:
        enabled: true
