imports:
    - { resource: parameters.yml }

parameters:
    locale: en

framework:
    secret: "%secret%"
    router:
        resource: "@RestBundle/Resources/config/routing.yml"
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_proxies: ~
    session: ~
    fragments: ~
    http_method_override: true
    serializer:
        enabled: true
    translator:
        enabled: true
