security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
    providers:
        in_memory: ~
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
